[package]
edition = "2021"
name = "trade-or-slay"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
pharos = "0.5"

macroquad = "0.3"
miniquad = "0.3.0-alpha.33"

resvg = "0.22.0"
tiny-skia = "0.6.3"
usvg = "0.22.0"

generational-arena = "0.2.8"
lazy_static = "1.4.0"
